# Generated by Django 5.0.2 on 2024-02-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartview', '0002_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
