# Generated by Django 5.0.2 on 2024-02-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartview', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='quarter',
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
