# Generated by Django 5.0.2 on 2024-02-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartview', '0005_remove_product_date_alter_product_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year_Quarter', models.CharField(default='', max_length=20, null=True, unique=True)),
                ('ProductA', models.IntegerField()),
                ('ProductB', models.IntegerField()),
                ('ProductC', models.IntegerField()),
            ],
        ),
    ]
