# Generated by Django 5.0.2 on 2024-02-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartview', '0007_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Number_of_oder',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
