# Generated by Django 5.0.2 on 2024-02-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartview', '0008_report_number_of_oder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Number_of_oder',
            new_name='Number_of_order',
        ),
    ]
