# Generated by Django 5.0.2 on 2024-03-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartview', '0009_rename_number_of_oder_report_number_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
