# Generated by Django 5.0.2 on 2024-03-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartview', '0010_alter_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Year_Quarter',
        ),
    ]
