# Generated by Django 5.0.2 on 2024-03-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartview', '0011_remove_report_year_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.CharField(default='未完成', max_length=40),
        ),
    ]
